### ISSUE TITLE
Barbarian is not working

### ISSUE THREAD

**Issue by Maquzowastaken** [HGLabor/HGLaborKitAPI2.0#109]
When u get kills your sword isn't upgrading

**Comment by copyandexecute** [comment]
Weißt du dass du in ffa 5 kills brauchst damit das schwert sich upgraded? oder ist es unabhängig davon?

**Comment by Maquzowastaken** [comment]
> Weißt du dass du in ffa 5 kills brauchst damit das schwert sich upgraded? oder ist es unabhängig davon?

Also als ich gestern gespielt habe, wurde nach jedem kill mein Schwert geupgradet. Gabs da ein update oder sowas?

**Comment by copyandexecute** [comment]
ne da wars einfach falsch eingestellt xd
