### ISSUE TITLE
beehive + gardener

### ISSUE THREAD

**Issue by zImFloydy** [HGLabor/HGLaborKitAPI2.0#132]
wenn jemand mit beehive honigblöcke unter sich spawnt und der gardener seine beerenbüsche spawnt droppen alle beeren die auf den honigblöcken spawnen als items

**Comment by zImFloydy** [comment]
nvm nicht nur die honigblöcke, jeder block außer dirt :)

**Comment by copyandexecute** [comment]
#139 fixed with <-
