### ISSUE TITLE
Gambler Items->Inv Bug

### ISSUE THREAD

**Issue by oSlxme** [HGLabor/HGLaborKitAPI2.0#144]
Wenn man mit Gambler bestimmte Items (z.B. Seeds, Steaks, Dried Kelp) gambelt, bekommt man bei weiteren malen diese Items nicht mehr ins Inv.
(bis jetzt nur in FFA getestet)

**Comment by soho030** [comment]
Sobald du ein Item aus dem Inventar entfernst. sollten die anderen Items erscheinen. Teste das mal bitte.

**Comment by oSlxme** [comment]
Hab jetzt auch mit leerem Inventar und Items droppen getestet, bringt aber nichts.
Hab diesmal auch 2 Screenshots aufgenommen
- beim ersten hab ich Seeds gegambelt: https://prnt.sc/11g2xxg
- beim zweiten hab ich nochmal Seeds gegambelt, jedoch keine weiteren bekommen: https://prnt.sc/11g31u9

**Comment by realjarek** [comment]
das gleich passiert bei mir auch wenn man recraft gambelt wenn man full inv hat dann bekommt man das rc nicht dazu also erst wenn man paar suppen dropt
