### ISSUE TITLE
Mouseabuse Bug 

### ISSUE THREAD

**Issue by NooMacroo** [HGLabor/HGLaborKitAPI2.0#145]
Sehr oft passiert das beim mouseabusen:
https://youtu.be/kWN6C9KyXzk
Dies ist kein Clip von mir und einer aus der 1.7 da kommt es auch mal vor aber sehr selten aber in der 1.16 ist das bei gefühlt jedem 2.Refill so (mit über 20CPS)

**Comment by Hotkeyyy** [comment]
das ist kein bug das ist wenn man irgendwie so doppelt auf eine suppe im inv klick ist nen feature von minecraft

**Comment by r0yzer** [comment]
du sagst doch selber dass es aus der 1.7 ist dann kann es doch nicht an labor liegen sondern ist wie hotkey gesagt hat ein minecraft feature denk bitte wenigstens ein ganz bischen nach

**Comment by Wxmble** [comment]
Sowas ist nicht serverseitig, sonder clientseitig. Da kann hglabor absolut nichts für

**Comment by helqless** [comment]
Man kann den Bug vermeiden indem man nicht mouse abused. 
Hoffe das hat geholfen :)

**Comment by NooMacroo** [comment]
> du sagst doch selber dass es aus der 1.7 ist dann kann es doch nicht an labor liegen sondern ist wie hotkey gesagt hat ein minecraft feature denk bitte wenigstens ein ganz bischen nach

In der 1.7 sehr sehr selten in der 1.16 aber sehr oft

**Comment by ichmagmaenner4** [comment]
mausabuse halt auf rechtsklick, ist ja nicht so als wärst du in 1.7 besser
