### ISSUE TITLE
Beequeen nach dem Tod

### ISSUE THREAD

**Issue by zImFloydy** [HGLabor/HGLaborKitAPI2.0#152]
wenn die Beequeen ihr Kit benutzt und somit die Honigblöcke unter jemandem spawnt und sie während das Kit "aktiv" ist stirbt bleiben Bienen und Honigblöcke auf dem Todesort vorhanden :) 
![Screenshot (181)](https://user-images.githubusercontent.com/82404889/114935226-3555b300-9e3b-11eb-874e-7a62d0262c8e.png)

**Comment by copyandexecute** [comment]
should be fixed with next restart
