### ISSUE TITLE
Kit: Hemomancer

### ISSUE THREAD

**Issue by Haxorzis** [HGLabor/HGLaborKitAPI2.0#163]
Ich hätte eine Kit Idee, die es so noch nicht gab. Es ist durch Hemomancy bzw. Blood Magic inspiriert.
Es ist eine Art Anti-Teaming Kit mit dem man, wenn man sich im Kampf befindet, jede Sekunde jedem Gegner innerhalb 5 Blöcken ein halbes Herz abzieht, und man sich selber um ein halbes heilt. Für jeden Gegner im umkreis heilt man sich natürlich um jeden Gegner mehr.

**Comment by Krxwallo** [comment]
r0yzer ich kann des coden xd nimm mir des net weg mach lieber anderes kit haha

**Comment by Haxorzis** [comment]
RoyalCheater*

**Comment by SoupOG** [comment]
Coole Idee
