### ISSUE TITLE
Swordman ein Schwert bleibt 

### ISSUE THREAD

**Issue by Naaaaaam** [HGLabor/HGLaborKitAPI2.0#215]
Ich glaube nicht, dass es gewollt ist, dass nachdem man die Fähigkeit geused hat und die Schwerter weg sind, man selbst dann wieder angreifen kann, ca. 10 Sekunden eines der Schwerter da bleibt und den Gegner auscrittet. Falls es doch gewollt ist, finde ich es relativ stark und eigentlich OP.

**Comment by Naaaaaam** [comment]
Länger als 10 Sekunden sogar, fast sogar solange bis der Gegner stirbt. Ist irgendwie immer unterschiedlicher

**Comment by mooziii** [comment]
was

**Comment by Naaaaaam** [comment]
Ich denke ich kann das Issue dann schließen, weil ich dir das ja über Discord erklärt habe.
