### ISSUE TITLE
50% poison chance

### ISSUE THREAD

**Issue by Stahli911** [HGLabor/HGLaborKitAPI2.0#223]
Bei dem Kit Viper bekommt man bei jedem 2. Hit poison obwohl es nur eine 33% chance gibt

**Comment by Indikativ** [comment]
cringe wer issue opened bevor man code liest
die warscheinlichkeit ist 30% btw

**Comment by Stahli911** [comment]
Es ist aber so das ich bei jedem zweiten hit poison bekomme

**Comment by Indikativ** [comment]
unlucky ¯\_(ツ)_/¯
