### ISSUE TITLE
Gambler Instant Death

### ISSUE THREAD

**Issue by wolkenpiste** [HGLabor/HGLaborKitAPI2.0#32]
Die Chance für den Instant Death beim Gambler-Kit ist zu hoch. Man bekommt diesen recht häufig, obwohl der Instant Death beim Gambler-Kit ein seltenes Event sein sollte.

**Comment by copyandexecute** [comment]
Die chance an sich ist gering nur es gibt noch keine anderen negativen effekt -> daher kommt einem das so oft vor

@mooziii wollte aber noch mehr effekte adden, bzw ich
