### ISSUE TITLE
Cooldown wird angezeigt, obwohl man nicht versucht die Fähigkeit zu verwenden

### ISSUE THREAD

**Issue by Wxffel** [HGLabor/HGLaborKitAPI2.0#39]
Bei Kits mit Cooldown, dessen Fähigkeit auslösen sollte, sobald man einen Spieler schlägt, wird der Cooldown auch angezeigt, wenn man Schaden durch einen Mob oder durch einen anderen Spieler erleidet.

Beispielsweise Gravity: Wenn man gerade Cooldown hat, wird dieser auch angezeigt wenn man geschlagen wird, obwohl man gar nicht versucht seine Fähigkeit einzusetzen.

**Comment by mooziii** [comment]
> Wenn man gerade Cooldown hat, wird dieser auch angezeigt wenn man geschlagen wird, obwohl man gar nicht versucht seine Fähigkeit einzusetzen.

Liegt wahrscheinlich daran, dass Gravity eine Funktion hat wenn man den Spieler schlagen will, diese aber dann durch den Cooldown abgebrochen wird und dann die Meldung kommt.

@copyandexecute Maybe eine `@IgnoreCooldown`-Annotation dafür?

**Comment by copyandexecute** [comment]
Das gravity beispiel stimmt nicht (mehr)?

**Comment by copyandexecute** [comment]
bei welchen kits ist das der fall

**Comment by Wxffel** [comment]
> Das gravity beispiel stimmt nicht (mehr)?

Man muss dabei das KitItem in der Hand halten.
