### ISSUE TITLE
/suicide bei Soulstealer macht unsterblich

### ISSUE THREAD

**Issue by mooziii** [HGLabor/HGLaborKitAPI2.0#51]
Wenn ich jemaden mit Soulstealer kille und dann suicide, droppt mein Stuff aber bin unsterblich

**Comment by Wxffel** [comment]
Dies gilt auch für das Kit "Scout" (:

**Comment by copyandexecute** [comment]
> 
> 
> Dies gilt auch für das Kit "Scout" (:

what? pls genauer

**Comment by Wxffel** [comment]
Es droppen die Inventory Contents, aber man behält trotzdem seinen Stuff - man ist anschließend unsterblich, macht aber auch keinen Damage mehr und kann mit nichts mehr interagieren. Da man auch nach einem Rejoin den Kitselector nicht wieder bekommt, kann man dann nicht mehr spielen.

**Comment by Wxffel** [comment]
It is fixed!
