### ISSUE TITLE
Digger Kit-Item

### ISSUE THREAD

**Issue by wolkenpiste** [HGLabor/HGLaborKitAPI2.0#8]
Die Dracheneier des Digger-Kit werden nach dem Platzieren nicht weniger. Außerdem kann mit mit Digger den enchanter aus dem Feast entfernen.

**Comment by copyandexecute** [comment]
"Außerdem kann mit mit Digger den enchanter aus dem Feast entfernen." soll man doch können oder?

**Comment by copyandexecute** [comment]
Fixxed, not tested yet
