### ISSUE TITLE
Hulk Endermage

### ISSUE THREAD

**Issue by r0yzer** [HGLabor/HGLaborKitAPI2.0#86]
Wenn ein Hulk mit Spieler drauf maged wird wird nur der sitzende Spieler maged

**Comment by r0yzer** [comment]
und anscheinend ist dieser spieler dann dauerhaft unverwundbar und kann kein angreifen (also in der mage protection stuck)

**Comment by copyandexecute** [comment]
wird gleich auf ffatest hochgeladen, bitte testen und schließen oder schreiben ob noch bugged
