### ISSUE TITLE
Kangaroo deaktivierung

### ISSUE THREAD

**Issue by Wxffel** [HGLabor/HGLaborKitAPI2.0#87]
Wenn das Kit "Kangaroo" durch das Kit "Rogue" deaktiviert wird und man anschließend mit dem Kititem von (Rakete) den Boden rechtsklickt, fliegt diese Weg und man kann das Kit Kangaroo nicht mehr einsetzen :|

**Comment by copyandexecute** [comment]
hahahahahaha

**Comment by copyandexecute** [comment]
fix ich

**Comment by r0yzer** [comment]
hahah

**Comment by copyandexecute** [comment]
pls check and close if fixed
